### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by jimmy-23** [rjhornsby/churchill-solver#1]
When I run the code it gives me a file not found error.

```
File "/Users/xxx/Downloads/churchill-solver-master/lib/deck.py", line 28, in load_dealpack with open('deal_packs/dealpack_1.json') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'deal_packs/dealpack_1.json'
```

Is it possible to get this file or at least the format so I can create my own?

**Comment by rjhornsby** [comment]
Added assets to the repo. Sorry, this is currently a quite incomplete implementation, very much a work in progress.
